### ISSUE TITLE
enchance-bro

### ISSUE THREAD

**Issue by enigm4s** [aztecrabbit/bugscanner#1]
so, any plan for little update or adding enchancement to this tool ?
I like the direct part of this tool, for some reason, I just had this one and the other tool that can be used to make "direct access" to a site.

how 'bout the ability to add a list of proxy in .txt,.lst,.etc... ??
it'll add strength +100 to this tool ;D

(I use linggis, just in case someone out there reading, not from the wkwkwkland)

-nub bug bunter ;)

**Comment by aztecrabbit** [comment]
Ya, tool ini bakal dibagusin nanti, tapi nanti. Kalo mau nyumbang ide atau pull silahkan.

> how 'bout the ability to add a list of proxy in .txt,.lst,.etc

Oke, bakal ditaro di list. tapi buka issue lagi aja om, biar gampang nyortir feature requestnya (mau dilabelin), issue ini mau di close.
