### ISSUE TITLE
Status Codes do not show on the result

### ISSUE THREAD

**Issue by Digital-XxX** [aztecrabbit/bugscanner#8]
I tried it hoping it'll show the status code of the website. And i hope this gets an upgrade like scan an entire CIDR.

**Comment by aztecrabbit** [comment]
> I tried it hoping it'll show the status code of the website.

It is. If status code not showing, maybe the ip or hostname is dead, or the request is timeout.

> And i hope this gets an upgrade like scan an entire CIDR.

Okeee, scan based on CIDR wold be awesome.

Btw, are you Indonesian?

**Comment by Digital-XxX** [comment]
Nope. I'm a Filipino.
